name: Backend Pipeline

# Workflow triggers
on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  # Schedule pipeline to run everyday midnight
  schedule:
    - cron: 0 0 * * *
  # Enable manual runs of workflow
  workflow_dispatch:

# Workflow stages
jobs:      
  # Perform Lint Checks
  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Install pnpm package manager
      run: npm install -g pnpm
    - name: Install Dependencies
      run: pnpm install
    - name: Run lint script
      run: pnpm run lint

  # Run Unit Tests
  test:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies with pnpm
      run: pnpm install
    - name: Run unit tests with jest
      run: echo "No unit tests exist yet. Skipping."

  # Build Application
  build:
    name: Build Application
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: echo "No builds yet. Skipping."

  # Deploy Application
  deploy:
    name: Deploy Application
    needs: build
    if: github.event_name == 'schedule' # only deploy application based on the schedule
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: echo "No deployments yet. Skipping."

  # Notify After Deployment
  notify:
    name: Send Notifications
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification
      run: echo "No notifications yet. Skipping."

# Run unit tests for each OS version and Node version
  # test:
  #   name: Unit Tests [${{ matrix.os }}] [Node ${{ matrix.node_version }}] 
  #   needs: lint
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       node_version: [16.x, 18.x, 20.x]
  #       os: [ubuntu-latest, windows-latest, macOS-latest]   
  #   defaults:
  #     run:
  #       working-directory: ./backend
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node_version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node_version }} 
  #   - name: Install pnpm
  #     run: npm install -g pnpm
  #   - name: Install dependencies with pnpm
  #     run: pnpm install
  #   - name: Run unit tests with jest
  #     run: echo "No unit tests exist yet. Skipping."

