name: Frontend Pipeline

# Workflow triggers
on:

  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - '.github/workflows/backend_pipeline.yml'
  pull_request:
    branches:
      - 'main'
    paths: 
      - 'backend/**'
      - '.github/workflows/backend_pipeline.yml'
  schedule:
    - cron: 0 0 * * MON   # Schedule pipeline to run monday midnight after sunday ends
  workflow_dispatch:      # Enable manual runs of workflow

jobs:
  lint:
    name: Style Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: dart analyze

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: |
          flutter test \
          echo "no tests yet"

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: echo "no tests yet"
